### ISSUE TITLE
Hackathon: add `generic_ir_from_biocypher()` function to ingest TCR data

### ISSUE THREAD

**Issue by slobentanzer** [scverse/scirpy#404]
We will prepare a PR that generalises `datasets.vdjdb()` to ingest any immune receptor data that was preprocessed by BioCypher, to yield a generic AnnData object that can be flexibly updated and maintained.

**Comment by grst** [comment]
Hi @slobentanzer, 

has anything happend in the meanwhile on integrating BCR/TCR data into Biocypher? I am asking this because in #469 it surfaces that providing access to reference databases becomes a real data curation effort rather than just downloading and transforming a table. It would be nice to separate this from scirpy and have scirpy just obtain this from a knowledge graph. 

This would also require that there's an API to a publicly available biocypher knowledge graph - I'm not even sure if this is a plan at the moment?

**Comment by slobentanzer** [comment]
Hi @grst, thanks for the reminder! Honestly it dropped off my radar since I have been busy with the LLM extension framework BioChatter, but I am still committed to doing this.

We are in fact planning several developments for making available a public (generic) API, and we have some projects that also created specific APIs on their own. I would be happy to have a meeting about specific requirements in the scirpy case.

**Comment by grst** [comment]
Open points to finalize this

 - [x] commit rights to IggyTop repo for @grst 
 - [x] automate release of IggyTop (github release pushes updated version to zenodo) -> https://github.com/biocypher/iggytop/issues/25
    - [ ] cache dir using github actions (consider cache lifetime)
 - [x] documentation of IggyTop repo (what were the data curation steps, how to rebuild, ...) -> https://github.com/biocypher/iggytop/issues/30
 - [x] clarify hosting (scverse aws vs. zenodo vs. github releases) -> github releases or zenodo initially. Github releases might be easier to automate? 
 - [x] add function to `scirpy.datasets()` -> #652 
 - [x] test and compare results to previous vdjdb version
 - [x] update scirpy tutorial


Additional fields:
 - [x] original source database for each annotation https://github.com/biocypher/iggytop/issues/26
 - [x] Database metadata: download URL, version, date retreived -> https://github.com/biocypher/iggytop/issues/27


Input from Immunologist: 

- Harmonization steps revision (Do they make sense? Additional harmonization steps?)
- Which AIRR fields in addition to the existing ones would be good to have (eg. CDR3 nucleotide seq)
- Advice on quality scores
